CREATE DATABASE IF NOT EXISTS dht22;
USE dht22;

CREATE TABLE IF NOT EXISTS dht22_readings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    temperature FLOAT NOT NULL,
    humidity FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);